apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firstArgoApp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khedetanay/k8s-playground.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: firstArgoApp